### PR TITLE
Fix Tilemap move item save

### LINKED ISSUE #1325: Tilemap doesn't detect when an item is moved via the player
## Summary

Title.

## Current Behavior

When placing/deleting an item using the tilemap editor, then saving, the tilemap will recognize all this and save it appropriately. When an item is moved by a player, then the map saved, the tilemap does not detect this.

https://github.com/RE-SS3D/SS3D/assets/41941008/dacae35b-b207-48b4-bb04-ca1e492f24b1

## Expected Behavior

The tilemap should detect this and it should be seen when loading a save.

### PR DESCRIPTION
**Pull request by worldreboot**
(AI generated PR description, but is accurate. Let me know if the code needs work.)

# Summary

This PR implements persistent saving for items moved by players during gameplay. Previously, only items placed or deleted through the Unity Tilemap editor were being saved to the map file. Items dropped or moved by players at runtime were not being tracked by the TileMap system, causing them to revert to their original positions after saving and loading the map.

The solution involves registering player-dropped items with the TileMap system so they are included in the save/load cycle, while preventing duplication issues that could occur when items are moved multiple times or when loading maps with existing scene items.

#### PR checklist
- [x] The game builds properly without errors.
- [x] No unrelated changes are present.
- [x] No "trash" files are committed.
- [x] Relevant code is documented.
- [ ] Update the related GitBook document, or create a new one if needed.

# Pictures/Videos
https://drive.google.com/file/d/1AyIAofUcfhQju4kCo0Xn__71JnGez9v_/view

# Testing

To test this PR:

1. **Basic Functionality**: Start a game, pick up an item from the world, drop it in a new location, save the map, then reload the map. The item should appear in the dropped location, not the original spawn location.

2. **Multiple Moves**: Pick up an item, drop it, pick it up again, drop it in another location, save and reload. The item should appear in the final dropped location.

3. **Editor vs Runtime**: Place items using the Tilemap editor and save - these should still work as before. Drop items as a player and save - these should now persist correctly.

4. **No Duplication**: Items should not duplicate when moved or when loading maps. Each item should appear only once in its correct location.

5. **Container Items**: Items in player inventories or containers should not be affected by the TileMap saving system.

#### Networking checklist
- [x] Works from host in host mode.
- [x] Works from server in server mode.
- [x] Works on server in client mode.
- [x] Works and is synchronized across different clients.
- [x] Is persistent.

# Changes

## Core Implementation

**`Assets/Scripts/SS3D/Systems/Inventory/Containers/Hand.cs`**
- Modified `PlaceHeldItemOutOfHand()` to register dropped items with the TileMap system
- Added dynamic `ItemObjectSo` lookup using `item.Asset.Id` instead of requiring manual assignment
- Added necessary using statements for `SS3D.Core` and `SS3D.Systems.Tile`

**`Assets/Scripts/SS3D/Systems/Tile/TileMap.cs`**
- Enhanced `PlaceItemObject()` to handle existing items and prevent duplication
- Added `UpdatePosition()` calls for already-tracked items to ensure position persistence
- Optimized `ClearAllItemsInScene()` to only clear untracked items, preventing unnecessary destruction
- Improved save/load logic to handle both editor-placed and player-dropped items

**`Assets/Scripts/SS3D/Systems/Tile/PlacedObjects/PlacedItemObject.cs`**
- Modified `Create()` method to accept existing GameObjects, preventing runtime duplication
- Added `UpdatePosition()` method to synchronize transform and internal save data
- Enhanced networking spawn logic to work with both new and existing items

## Code Cleanup

**`Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs`**
- Removed redundant `ItemObjectSo` field since `Asset` property provides the same information
- Removed unnecessary using statement for `SS3D.Systems.Tile`

**`Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/TileMapSaveTab.cs`**
- Removed `AssignItemObjectSoFields()` method and its automatic assignment logic
- Simplified save process since `ItemObjectSo` lookup is now handled dynamically

**`Assets/Scripts/SS3D/Systems/Inventory/Items/ItemUtility.cs`**
- Removed debug logs from `Place()` method for cleaner code

## Technical Notes

The implementation uses the existing `Asset` system to dynamically retrieve `ItemObjectSo` references at runtime, eliminating the need for manual prefab assignment. The `PlacedItemObject` component is used to track items in the world, with careful handling to prevent duplication when items are moved multiple times or when loading maps with existing scene items.

The solution maintains backward compatibility with editor-placed items while extending the save/load functionality to player interactions.

## Known Issues

- Items that spawn in the player's hand by default (loadout items) will still spawn in the player's hand on map reload, even if they were dropped. This is intentional behavior as the loadout system is separate from the TileMap system.

# Related issues/PRs

Closes #1325

### CODE REVIEW

**Comment by stilnat** [comment]
image

**Comment by stilnat** [comment]
if nobody checks before the end of the week, I'll check your PR next week thanks a lot for your work !

**Comment by worldreboot** [comment]
Let me know if it could have been implemented better or if I'm missing something. I'm new to the codebase, etc.

File: Assets/Scripts/SS3D/Systems/Inventory/Containers/Hand.cs [hunk 1]
```diff
@@ -124,13 +126,23 @@ public void CmdDropHeldItem()
...
                 return;
-            }
+            
             ItemInHand.GiveOwnership(null);
             Item item = ItemInHand;
             item.Container.RemoveItem(item);
             ItemUtility.Place(item, position, rotation);
+
+            // Register with TileMap for saving
+            var tileMap = SubSystems.Get<TileSubSystem>().CurrentMap;
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/Inventory/Containers/Hand.cs]:
```suggestion
            TileMap tileMap = SubSystems.Get<TileSubSystem>().CurrentMap;
```

File: Assets/Scripts/SS3D/Systems/Inventory/Containers/Hand.cs [hunk 2]
```diff
@@ -124,13 +126,23 @@ public void CmdDropHeldItem()
...
+            if (tileMap != null)
+            {
+                var itemObjectSo = SubSystems.Get<TileSubSystem>().GetAsset(item.Asset.Id) as ItemObjectSo;
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/Inventory/Containers/Hand.cs]:
```suggestion
                ItemObjectSo itemObjectSo = SubSystems.Get<TileSubSystem>().GetAsset(item.Asset.Id) as ItemObjectSo;
```

File: Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs [hunk 3]
```diff
@@ -7,6 +7,7 @@
 using FishNet.Object.Synchronizing;
 using SS3D.Attributes;
 using SS3D.Data.AssetDatabases;
+using SS3D.Data.Generated;
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs]:
```suggestion
```

File: Assets/Scripts/SS3D/Systems/Tile/PlacedObjects/PlacedItemObject.cs [hunk 4]
```diff
@@ -15,17 +15,30 @@ namespace SS3D.Systems.Tile
...
+                // Use the existing item GameObject
+                placedGameObject = existingItem;
+                placedGameObject.transform.SetPositionAndRotation(worldPosition, rotation);
+            }
+            else
+            {
+                // Create a new GameObject (for loading from save files)
+                placedGameObject = Instantiate(itemSo.prefab);
+                placedGameObject.transform.SetPositionAndRotation(worldPosition, rotation);
+            }
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/Tile/PlacedObjects/PlacedItemObject.cs]:
```suggestion
            if (existingItem != null)
            {
                // Use the existing item GameObject
                placedGameObject = existingItem;
            }
            else
            {
                placedGameObject = Instantiate(itemSo.prefab);
            }
            placedGameObject.transform.SetPositionAndRotation(worldPosition, rotation);
```

File: Assets/Scripts/SS3D/Systems/Tile/TileMap.cs [hunk 5]
```diff
@@ -296,9 +296,30 @@ private void ResetAdjacencies(PlacedTileObject placed, ITileLocation location, L
...
         }
 
-        public void PlaceItemObject(Vector3 worldPosition, Quaternion rotation, ItemObjectSo itemObjectSo)
+        public void PlaceItemObject(Vector3 worldPosition, Quaternion rotation, ItemObjectSo itemObjectSo, GameObject existingItem = null)
         {
-            PlacedItemObject placedItem = PlacedItemObject.Create(worldPosition, rotation, itemObjectSo);
+            // Handle existing items that already have a PlacedItemObject component
+            if (existingItem != null)
+            {
+                var existingPlacedItem = existingItem.GetComponent<PlacedItemObject>();
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/Tile/TileMap.cs]:
```suggestion
                PlacedItemObject existingPlacedItem = existingItem.GetComponent<PlacedItemObject>();
```

File: Assets/Scripts/SS3D/Systems/Tile/TileMap.cs [hunk 6]
```diff
@@ -329,12 +350,21 @@ public void Clear()
...
+                if (item != null && item.gameObject != null)
+                {
+                    item.DestroySelf();
+                }
+                itemsToRemove.Add(item);
+            }
+            
+            foreach (var item in itemsToRemove)
+            {
+                _items.Remove(item);
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/Tile/TileMap.cs]:
```suggestion
                while (_items.Count > 0)
            {
                PlacedItemObject item = _items.First();
                if (item != null && item.gameObject != null)
                {
                    item.DestroySelf();
                }
                
                _items.RemoveAt(0);
            }
```
Also overwrite lines above, github doesn't allow to comment them

File: Assets/Scripts/SS3D/Systems/Tile/TileMap.cs [hunk 7]
```diff
@@ -421,5 +455,35 @@ private void UpdateAllAdjacencies()
...
+                {
+                    continue;
+                }
+                
+                // Destroy items that are in the world but not tracked by TileMap
+                if (item.gameObject != null)
+                {
+                    DestroyImmediate(item.gameObject);
+                }
+            }
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/Tile/TileMap.cs]:
```suggestion
            Item[] allItems = FindObjectsOfType<Item>();
            
            foreach (Item item in allItems)
            {
                // Skip items that are in containers (player inventory, etc.)
                // and items that already have PlacedItemObject (they're already tracked)
                if (item.Container != null || item.GetComponent<PlacedItemObject>() != null)
                {
                    continue;
                }
                
                // Destroy items that are in the world but not tracked by TileMap
                if (item.gameObject != null)
                {
                    DestroyImmediate(item.gameObject);
                }
            }
```
If all items are either in containers or being tracked (as i understand), what is this function supposed to clear?

File: Assets/Scripts/SS3D/Systems/Tile/PlacedObjects/PlacedItemObject.cs [hunk 8]
```diff
@@ -15,17 +15,30 @@ namespace SS3D.Systems.Tile
     public class PlacedItemObject : NetworkBehaviour
     {
         /// <summary>
-        /// Creates a new PlacedItemObject from a prefab at a given position and rotation. Uses NetworkServer.Spawn() if a server is running.
+        /// Creates a new PlacedItemObject from an existing item GameObject at a given position and rotation.
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/Tile/PlacedObjects/PlacedItemObject.cs]:
```suggestion
        ///  Places an item on the tilemap at a given position and rotation
```

**Review by iamteapot422 — CHANGES_REQUESTED** [review]
Items are still being tracked if you put them into a container (reproducable by picking up an item and realoading the map)
Minor code style changes

File: Assets/Scripts/SS3D/Systems/Tile/TileMap.cs (hunk 7 above)
Comment (worldreboot) [reply Assets/Scripts/SS3D/Systems/Tile/TileMap.cs]: This function is mainly a defensive cleanup to remove any world items that aren't in containers and aren't tracked by the TileMap. Ideally, this function would do nothing, but it is mainly there to prevent issues from stray or untracked items (eg. items that were placed in the scene by the Unity Editor (not registered with the TileMap at runtime)). Let me know if this doesn't make any sense

**Comment by worldreboot** [comment]
What is the intended behaviour for picking up items then saving the map? Should the map reload with the item in hand? I guess in order to be consistent with my logic, I should remove the item in hand, and just save the position where the item was originally pickup up from and show the item there on reload?

File: Assets/Scripts/SS3D/Systems/Tile/TileMap.cs (hunk 7 above)
Comment (iamteapot422) [reply Assets/Scripts/SS3D/Systems/Tile/TileMap.cs]: Then it should log a warning about what items are being leftover. Also change the description and name to represent that the function deletes only items out of containers and without a tracker

**Comment by iamteapot422** [comment]
Anything that is picked up by a player shouldn't affect the tilemap. For example, if a player picks up a wrench and puts it in a pocket, and then saves the map, the wrench won't be saved. Same with loading, the algorithm shouldn't affect players. I guess removing PlacedItemObject after putting an item into a container would do the trick

**Comment by worldreboot** [comment]
@iamteapot422 Implemented a fix which removes PlacedItemObject when an item is placed in a container, preventing them from being saved with the tilemap. Now if a player picks up an item and saves the map with it in a container, the item is removed from the map on save, and the players remain unaffected on map loads. Let me know if this is fine

**Review by iamteapot422 — APPROVED** [review]
Good job. What's your nickname on Discord?

**Comment by worldreboot** [comment]
I am @liglius

**Comment by iamteapot422** [comment]
Join our server so we can send you the bounty https://discord.gg/Jdfwk9GR
