### PR TITLE
Fix chat message sending when out of focus

### LINKED ISSUE #782: Chat will send when clicking screen anywhere
## Current Behavior

The chat system sends the message when clicking anywhere on the screen. This is not the intended design.

## Expected Behavior

The chat system should send when clicking only on the send button on the lower right corner of the chat window, but not by clicking anywhere else.

### PR DESCRIPTION
**Pull request by nsarrazin**
## Summary

This PR fixes issue #782 regarding messages sending when the window goes out of focus. It also adds the ability to send a message by pressing Enter.

## Changes to Files
* `ChatWindow.cs` has been updated a bit, I added a couple of methods.
* `ChatWindow.prefab` has also been updated. I linked new methods to the onSelect and onDeselect callbacks (?) of the text input.

## Technical Notes (optional)

* `ChatWindow` now has a `isSelected` public attribute that is true when the input field is in focus.
* `ChatWindow` has an `Update` method that checks if Enter is pressed and if the input field is in focus, and sends the message if that's the case. 
* The call to unfocus the input field after a message is sent has been moved to the end of the `SendMessage` method.  

## Fixes (optional)
Fixes #782

### CODE REVIEW

**Review by cosmiccoincidence — COMMENTED** [review]
It seems like you fixed the problem mentioned in the linked issue, but...

> It also adds the ability to send a message by pressing Enter.

I believe this was already possible before, and I believe using the ENTER key on the numpad also worked before but the numpad ENTER key no longer works now.

**Comment by nsarrazin** [comment]
I believe the reason it was possible before was because pressing enter on the keyboard/keypad would make the input field go out of focus which would send the message. 

I've added a check for `KeypadEnter` the same way I do for `Return` this should be fixed but I don't actually own a keypad so if you could check if it works that would be great.

File: Assets/Engine/Chat/ChatWindow.cs [hunk 1]
```diff
@@ -218,15 +221,27 @@ public bool PlayerIsTyping()
...
+        }
+
+        public void onDeselect()
+        {
+            this.isSelected = false;
+        }
+
+        public void Update()
+        {
+            if ((Input.GetKeyUp(KeyCode.Return) || Input.GetKeyUp(KeyCode.KeypadEnter) && this.isSelected)
```
Comment (Ryan089) [inline Assets/Engine/Chat/ChatWindow.cs:241]: I'm getting a compile-time error here. There are more open brackets than close brackets.

Comment (nsarrazin) [reply Assets/Engine/Chat/ChatWindow.cs]: Whoops should have tested that, it's fixed now.

**Comment by nsarrazin** [comment]
I cleaned this up a lot, turns out there was a way more elegant implementation possible !

**Review by cosmiccoincidence — APPROVED** [review]
Looks good!
