### PR TITLE
fix command system

### LINKED ISSUE #1233: Command should be called by clients and executed on server
## Summary

Currently, some commands (the console command popping when pressing F12) have to be launch from host (since it's also server), and it doesn't allow a client admin to execute commands such as spawning items server wise.
Find a way to allow authorized clients to execute commands server side.

## Possible solutions

Alain's suggestion : 

> you could mark a command as "run on server"
if the command parser on the client gets a command with that info, it sends the whole command string to the server
the server uses the same parser and actually executes the command

IamTeapot suggested to use a decorator (need more info)

### PR DESCRIPTION
**Pull request by stilnat**
## Summary

This PR allows command to be executed server or client side, by anyone with the correct authorizations (admin, user, etc...).
It fixes a few issues with command not being able to be called by clients.

## Changes to Files

- CommandController is now a network actor

## Known issues

I get the following issues :
- I get message  `The referenced script (Unknown) on this Behaviour is missing!`
- I get `The referenced script on this Behaviour (Game Object '<null>') is missing!`

Those two warnings don't seem to impact anything, but I can't find the source of it.

Closes #1233

### CODE REVIEW

**Comment by Alainx277** [comment]
The changes in general look good. It would be nice if you could look up the command on the client and see if it is client only and doesn't require permissions, then run it locally directly. I think for example the reconnect command should also work if you get disconnected.

P.S. Nice PR number

File: Assets/Scripts/SS3D/Systems/IngameConsoleSystem/Commands/KillCommand.cs [hunk 1]
```diff
@@ -10,17 +12,22 @@ public class KillCommand : Command
...
+
+        [Server]
+        public override string Perform(string[] args, NetworkConnection conn = null)
         {
             CheckArgsResponse checkArgsResponse = CheckArgs(args);
             if (checkArgsResponse.IsValid == false)
                 return checkArgsResponse.InvalidArgs;
             string ckey = args[0];
             Player PlayerToKill = Subsystems.Get<PlayerSystem>().GetPlayer(ckey);
             Entity entityToKill = Subsystems.Get<EntitySystem>().GetSpawnedEntity(PlayerToKill);
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/IngameConsoleSystem/Commands/KillCommand.cs]:
```suggestion
            Player playerToKill= Subsystems.Get<PlayerSystem>().GetPlayer(ckey);
            Entity entityToKill = Subsystems.Get<EntitySystem>().GetSpawnedEntity(playerToKill);
```

Comment (iamteapot422) [reply Assets/Scripts/SS3D/Systems/IngameConsoleSystem/Commands/KillCommand.cs]: Rename PlayerToKill to playerToKill in CheckArgs() too, please

File: Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs [hunk 2]
```diff
@@ -2,11 +2,19 @@
...
 using System.Reflection;
+using FishNet.Connection;
+using FishNet.Object;
+using SS3D.Core;
+using SS3D.Core.Behaviours;
 using SS3D.Systems.IngameConsoleSystem.Commands;
+using SS3D.Systems.Permissions;
+using SS3D.Systems.PlayerControl;
+using UnityEngine;
+using UnityEngine.InputSystem;
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs]:
```suggestion
```

File: Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs [hunk 3]
```diff
@@ -16,7 +24,10 @@ public class CommandsController
         /// Length of space between columns in help command
         /// </summary>
         private const int TabLength = 20;
-        public CommandsController()
+
+        [SerializeField] private ConsolePanelView console;
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs]: Rename to _console

File: Assets/Scripts/SS3D/Systems/IngameConsoleSystem/ConsolePanelView.cs [hunk 4]
```diff
@@ -1,10 +1,12 @@
-using System;
+﻿using System;
 using System.Collections.Generic;
 using System.Linq;
 using Coimbra;
 using Coimbra.Services.Events;
 using Coimbra.Services.PlayerLoopEvents;
+using FishNet.Object;
 using SS3D.Core;
+using SS3D.Core.Behaviours;
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/IngameConsoleSystem/ConsolePanelView.cs]:
```suggestion
```

File: Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs [hunk 5]
```diff
@@ -29,33 +40,83 @@ public CommandsController()
...
+            if (_allCommands[commandName].ServerCommand)
+            {
+                RpcCommandAnswer(conn, _allCommands[commandName].Perform(command.Split().Skip(1).ToArray(), conn));
+                return;
+            }
+            else
+            {
+                RpcPerformOnClient(conn, command);
+                return;
+            }
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs]:
```suggestion
            if (_allCommands[commandName].ServerCommand)
            {
                RpcCommandAnswer(conn, _allCommands[commandName].Perform(command.Split().Skip(1).ToArray(), conn));
            }
            else
            {
                RpcPerformOnClient(conn, command);
            }
```

**Review by iamteapot422 — CHANGES_REQUESTED** [review]
Awesome work

**Comment by stilnat** [comment]
Thanks @Alainx277 , yes I thought about adding the client only thing but was too lazy, but since someone noticed I'll add it, it can definitely be useful for some commands.

File: Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs [hunk 6]
```diff
@@ -29,33 +40,83 @@ public CommandsController()
...
                 {
-                    return LongHelpCommand(command);
+                    RpcCommandAnswer(conn, LongHelpCommand(command));
+                    return;
                 }
             }
-            // Find proper command body and prepare correct args
-            if (_allCommands.ContainsKey(commandName))
+
+            if (!_allCommands.ContainsKey(commandName))
```
Comment (xk0fe) [inline Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs:160]:
```suggestion
            if (!_allCommands.TryGetValue(commandName, out var value))
```
This will allow us to get rid of access duplications like ```_allCommands[commandName]``` 
And change code below accordingly
```
if (value.AccessLevel > userPermission)
{
    RpcCommandAnswer(conn, "Access level too low, can't perform command");
    return;
}

if (value.ServerCommand)
{
    RpcCommandAnswer(conn, value.Perform(command.Split().Skip(1).ToArray(), conn));
    return;
}
```

The naming of a variable ```value``` might be not ideal and I would suggest to think more about it

File: Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs [hunk 7]
```diff
@@ -29,33 +40,83 @@ public CommandsController()
...
+            }
         }
+
+        [TargetRpc]
+        public void RpcPerformOnClient(NetworkConnection conn, string command)
+        {
+            string[] splitCommand = command.Split(' ');
+            string commandName = splitCommand[0];
+            string answer = _allCommands[commandName].Perform(command.Split().Skip(1).ToArray());
+            console.AddText(answer);
```
Comment (xk0fe) [inline Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs]:
```suggestion
        string[] splitCommand = command.Split(' ');
        if (splitCommand.Length <= 0)
        {
            console.AddText("Command is empty");
            return;
        }
        string commandName = splitCommand[0];
        if (!_allCommands.TryGetValue(commandName, out var commandHandler))
        {
            console.AddText("No such command exists");
            return;
        }
        string[] arguments = splitCommand.Skip(1).ToArray();
        string answer = commandHandler.Perform(arguments);
        console.AddText(answer);
```

Command is missing necessary safety checks

**Review by xk0fe — CHANGES_REQUESTED** [review]
Great, I like it

File: Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs [hunk 8]
```diff
@@ -41,80 +41,176 @@ protected override void OnStart()
...
+            if (TreatHelpCommand(null, command, commandName, splitCommand))
+            {
+                return;
+            }
+            
+            if (commandObject.Type != CommandType.Offline)
+            {
+                CommandAnswer(null, "Can't execute offline, non offline commands.");
+                return;
+            }
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs]:
```suggestion
```
Redundant

File: Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs [hunk 9]
```diff
@@ -41,80 +41,176 @@ protected override void OnStart()
...
+        }
+
         /// <summary>
         /// Find and call command
         /// </summary>
         /// <param name="command">Command and it's args separated by spaces</param>
         /// <returns>Command response</returns>
         [ServerRpc(RequireOwnership = false)]
-        public void CmdProcessCommand(string command, NetworkConnection conn = null)
+        private void CmdProcessCommand(string command, NetworkConnection conn = null)
```
Comment (iamteapot422) [inline Assets/Scripts/SS3D/Systems/IngameConsoleSystem/CommandsController.cs]: Rename to OnlineProcessCommand

**Review by iamteapot422 — CHANGES_REQUESTED** [review]

**Review by iamteapot422 — APPROVED** [review]
