### PR TITLE
Activate ragdoll after death

### LINKED ISSUE #1351: Body continues animation even after entity died
## Summary

Dead bodies seem to continue animating after the parent entity has died.

The only example I have tested myself is running and killing yourself at the same time.

## Steps to Reproduce

- start round
- start running
- killed self while running

## Expected Behavior

Dead bodies should not be animated (typically).

## Video

https://github.com/RE-SS3D/SS3D/assets/41941008/68fee6c4-637f-43bf-ac46-4eb36798f663

### PR DESCRIPTION
**Pull request by iamteapot422**
Literally what the title says

#### PR checklist
- [x] The game builds properly without errors.

- [x] No unrelated changes are present.

- [x] No "trash" files are committed.

- [x] Relevant code is documented.

# Testing
Enter "kill (ckey)" in command console

#### Networking checklist

- [x] Works from host in host mode.

- [x] Works from server in server mode.

- [x] Works on server in client mode.

- [x] Works and is syncronized across different clients.

- [x] Is persistent.

# Related issues/PRs 
Closes #1351 
Corpses fly in a funny after if they hold an item. Caused by collision between items and hands

### CODE REVIEW

**Comment by stilnat** [comment]
If possible, I'd like this PR to also add ragdoll upon death through damages, not only by using a command. Ragdoll should activate when the body do not contain any entity, upon head being crushed or decapitated.

File: Assets/Scripts/SS3D/Systems/Health/BodyParts/HumanTorso.cs [hunk 1]
```diff
@@ -58,6 +57,19 @@ protected override void AddInitialLayers()
 
         InvokeOnBodyPartLayerAdded();
     }
+    
+    protected override void InflictDamage(BodyLayer layer, DamageTypeQuantity damageTypeQuantity)
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Health/BodyParts/HumanTorso.cs]: why is this needed ? remember, the expected behavior for the health system is that the human dies only when its brain dies.

File: Assets/Scripts/SS3D/Systems/Health/BodyParts/HeadBodyPart.cs [hunk 2]
```diff
@@ -81,14 +75,26 @@ protected override void BeforeDestroyingBodyPart()
             GetComponentInParent<Human>()?.DeactivateComponents();
         }
 
+        protected override void InflictDamage(BodyLayer layer, DamageTypeQuantity damageTypeQuantity)
+        {
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Health/BodyParts/HeadBodyPart.cs]: same here, the player should not die when the head is severed, only when the brain dies

**Review by stilnat — CHANGES_REQUESTED** [review]
first quick review

File: Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs [hunk 3]
```diff
@@ -69,29 +66,23 @@ public abstract class BodyPart : InteractionTargetNetworkBehaviour
...
 
     public Collider BodyCollider => _bodyCollider;
-
     public string Name => gameObject.name;
 
     /// <summary>
     /// Check if this bodypart has been detached. Should always be true for all bodyparts spawned on detach.
     /// </summary>
-    private bool _isDetached;
+    protected bool _isDetached;
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs]: I rather keep that one private but you can add a public or protected property to get its value

File: Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs [hunk 4]
```diff
@@ -202,7 +191,7 @@ public void SetParentBodyPart(BodyPart value)
     /// Implementation should handle instantiating _bodyPartItem, removing the bodypart game object and doing whatever else is necessary.
     /// </summary>
     [Server]
-    private void DetachBodyPart()
+    protected void DetachBodyPart()
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs]: I'd like to keep this method private, as it's gonna get a complete mess very soon if we don't. can you maybe instead use the events, or the abstract methods to do what you want to do ?

File: Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs [hunk 5]
```diff
@@ -259,12 +248,11 @@ protected virtual void CopyValuesToBodyPart(BodyPart bodyPart)
     /// All child body parts are detached, all internal body parts are destroyed.
     /// </summary>
     [Server]
-    private void DestroyBodyPart()
+    protected void DestroyBodyPart()
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs]: Same for this one, keep it private, use events or abstract methods to implement particular behavior.

File: Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs [hunk 6]
```diff
@@ -415,6 +403,14 @@ public bool TryInflictDamage(BodyLayerType type, DamageTypeQuantity damageTypeQu
 
         BodyLayer layer = FirstBodyLayerOfType(type);
         if (!BodyLayers.Contains(layer)) return false;
+        InflictDamage(layer, damageTypeQuantity);
+
+        OnDamageInflicted?.Invoke(this, EventArgs.Empty);
+        return true;    
+    }
+
+    protected virtual void InflictDamage(BodyLayer layer, DamageTypeQuantity damageTypeQuantity)
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs]: Github change comparisons is unreadable for me there .... I'm not sure what's going on despite having the code open, can you explain the changes ?

File: Assets/Scripts/SS3D/Systems/Health/BodyParts/HeadBodyPart.cs [hunk 7]
```diff
@@ -81,14 +76,26 @@ protected override void BeforeDestroyingBodyPart()
             GetComponentInParent<Human>()?.DeactivateComponents();
         }
 
+        protected override void InflictDamage(BodyLayer layer, DamageTypeQuantity damageTypeQuantity)
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Health/BodyParts/HeadBodyPart.cs]: here we have custom logic only when the head is severed, instead of overriding a method that has no direct relation to severing logic, can you maybe use an event or one of the abstract method ?

File: Assets/Scripts/SS3D/Systems/Health/BodyParts/HumanTorso.cs [hunk 8]
```diff
@@ -58,6 +57,15 @@ protected override void AddInitialLayers()
...
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Health/BodyParts/HumanTorso.cs]: I don't really see the custom logic in there. Why is this needed ?

**Review by stilnat — CHANGES_REQUESTED** [review]
The Bodypart script was designed the following way, keep private as much as possible base behaviors of body parts, use events or abstract methods to implement custom logic when needed. It was not documented enough, my bad. 

Can you try to reimplement your logic this way instead of using protected virtual method ? I'm afraid the body parts are going to become a huge unreadable mess if we use too much inheritance mechanics.

Let me know if I can help, or if there's some parts where setting method protected seems unavoidable.

File: Assets/Scripts/SS3D/Systems/Health/BodyParts/HumanTorso.cs (hunk 8 above)
Comment (iamteapot422) [reply Assets/Scripts/SS3D/Systems/Health/BodyParts/HumanTorso.cs]: Torso isn't detached upon reaching max damage

Comment (stilnat) [reply Assets/Scripts/SS3D/Systems/Health/BodyParts/HumanTorso.cs]: Please let reviewer resolve conversations. I get what you need to do, but I rather have this method stay private (at least not virtual). Can we instead have a virtual IsDetachable property on body parts ? true for most and false for torso ? And use this property with a if in the Inflict damage method (only detach if it's detachable)

File: Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs (hunk 6 above)
Comment (iamteapot422) [reply Assets/Scripts/SS3D/Systems/Health/BodyParts/Bodypart.cs]: I've extracted InflictDamage code from TryInflictDamage to override it after in child classes

**Review by stilnat — APPROVED** [review]
