### PR TITLE
Fix Stored Items Rendered in Inventory

### LINKED ISSUE #1167: Child Items Rendered in Inventory
## Summary

It appears that items inside of other items are still rendered in the inventory.

## Steps to Reproduce

Start the game and notice the PDA in your inventory looks funny. Upon closer inspection you will see that the ID card that is inside it is also being rendered, overlapping with the PDA.

image

### PR DESCRIPTION
**Pull request by iamteapot422**
## Known issues
You can interact with stored items. Not related to this pr.

## Fixes
Closes #1167 
Fix preview generations every time item is moved to container
Fix only one part of stored item set to invisible
Clean the code up a bit

### CODE REVIEW

File: Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs [hunk 1]
```diff
@@ -185,26 +182,21 @@ public void Unfreeze()
...
         /// <param name="visible">Should the item be visible</param>
         [Server]
         public void SetVisibility(bool visible)
         {
             // TODO: Make this handle multiple renderers, with different states
-            Renderer renderer = GetComponentInChildren<Renderer>();
+            Renderer[] renderers = GetComponentsInChildren<Renderer>();
 
-            if (renderer != null)
+            foreach (Renderer renderer1 in renderers)
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs]: renderer1 is a weird name

File: Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs [hunk 2]
```diff
@@ -100,10 +99,16 @@ public void Init(string name, float weight, Vector2Int size,  List<Trait> traits
         /// <summary>
         /// The sprite that is shown in the container slot
         /// </summary>
-
         public Sprite Sprite
         {
-            get => InventorySprite();
+            get
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs]: I think john rather have a method to call in the getter instead of the long getter, put that back in its initial state.

File: Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs [hunk 3]
```diff
@@ -78,19 +77,19 @@ public class Item : InteractionSource, IInteractionTarget
 
         public Container Container => _container;
 
-        private bool _initialised = false;
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs]: to me it's clearer to keep the "= false", even though it's the default value, it also points out that it should not have any other value initialised with.

**Review by stilnat — CHANGES_REQUESTED** [review]
Good stuff, small changes to do. Will test tomorrow.

File: Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs (hunk 1 above)
Comment (iamteapot422) [reply Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs]: is childRenderer better? Just renderer is already taken

Comment (stilnat) [reply Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs]: Yeah childrenderer works

File: Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs [hunk 4]
```diff
@@ -285,29 +280,59 @@ public void SetContainer(Container newContainer)
...
+        // Generate preview of the same object, but without stored items.
         [ServerOrClient]
-        public Sprite GenerateNewIcon()
+        public Sprite GenerateIcon()
         {
             RuntimePreviewGenerator.BackgroundColor = new Color(0, 0, 0, 0);
             RuntimePreviewGenerator.OrthographicMode = true;
-
+            // Find stored items
+            AttachedContainer container = GetComponent<AttachedContainer>();
```
Comment (stilnat) [inline Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs]: this part is buggy for items with no containers, and probably for items with multiple containers too. You can safely assume the item script will be at the top of the item game object hierarchy so you can use GetComponentsInChildren to get all attached containers and iterate through that.

**Review by stilnat — CHANGES_REQUESTED** [review]

File: Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs (hunk 4 above)
Comment (iamteapot422) [reply Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs]: GetComponentsInChildren will get containers from  contained items

Comment (stilnat) [reply Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs]: Ho right silly me. You can use the containerInteractive reference then, or maybe use GetComponentsInChildren and keep only those that don't have an item script different from the item we want to show up in the hierarchy, that should safely eliminate containers from contained items.

Either way, your changes should work for multiple and no containers.

Comment (iamteapot422) [reply Assets/Scripts/SS3D/Systems/Inventory/Items/Item.cs]: containerInteractive is not bugproof, because not all containers may have it in the future, so i guess GetComponentsInChildren is the only way.

**Review by stilnat — APPROVED** [review]
good work
