### PR TITLE
Corrects issue where items are not on the Item layer.

### LINKED ISSUE #735: Some Items not on 'Item' layer
## Summary

Some items are on the wrong layer it seems.

Unity_rJe06w5u5W

Some things in the image are furniture (booze dispenser) or entities (corgi) but there are some items here that need moving to the 'Item' layer. Some visible ones are the flashlight, batteries, crayons, and beakers.

### PR DESCRIPTION
**Pull request by Ryan089**
## Summary

Prefabs for all offending Items have been placed in the correct layer. Additionally, any Item that spawns on the incorrect layer will now have a warning during Awake(), so that the developer can resolve the issue.

## Fixes

Closes #735

### CODE REVIEW

File: Assets/Engine/Inventory/Item.cs [hunk 1]
```diff
@@ -85,6 +85,12 @@ public Container Container
         public void Awake()
         {
             sprite = null;
+
+            // Add a warning if an item is not on the Item layer (layer 16).
+            if (gameObject.layer != 16)
+            {
+                Debug.LogWarning("Item " + Name + " is on layer " + gameObject.layer);
```
Comment (cosmiccoincidence) [inline Assets/Engine/Inventory/Item.cs:92]: Inconsistent spacing on `"Item "`?

File: Assets/Content/Items/Functional/Containers/Liquid/mug.prefab [hunk 2]
```diff
@@ -96,8 +96,8 @@ GameObject:
   - component: {fileID: -7777233483341371724}
   - component: {fileID: -6476219540935553843}
   - component: {fileID: 5848840416633041717}
-  m_Layer: 0
-  m_Name: Mug
+  m_Layer: 16
+  m_Name: mug
```
Comment (cosmiccoincidence) [inline Assets/Content/Items/Functional/Containers/Liquid/mug.prefab:100]: Keep this capitalized (same with the file name).

File: Assets/Content/Items/Functional/Containers/Liquid/beaker.prefab [hunk 3]
```diff
@@ -17,8 +17,8 @@ GameObject:
   - component: {fileID: 6346642276291690734}
   - component: {fileID: 3546999150553349723}
   - component: {fileID: 3570669310606646338}
-  m_Layer: 0
-  m_Name: Beaker
+  m_Layer: 16
+  m_Name: beaker
```
Comment (cosmiccoincidence) [inline Assets/Content/Items/Functional/Containers/Liquid/beaker.prefab:21]: Keep this capitalized (same with the file name).

**Review by cosmiccoincidence — CHANGES_REQUESTED** [review]

File: Assets/Engine/Inventory/Item.cs (hunk 1 above)
Comment (Ryan089) [reply Assets/Engine/Inventory/Item.cs:92]: This is simply the format of the warning message sentence. Removing the space would result in a message like: "ItemMug is on layer 0".

Comment (cosmiccoincidence) [reply Assets/Engine/Inventory/Item.cs:92]: Oh, ok.

**Comment by Ryan089** [comment]
While I've got no objections in principle with amending the names (though I didn't touch them in the first place, so not sure why they are changed), Unity is throwing some random errors when I try to amend them. I recommend that you either merge the PR as is, or you close it without merging and someone else can take this task.

**Review by cosmiccoincidence — APPROVED** [review]
