### PR TITLE
Fix ready button issue with non-admin clients

### LINKED ISSUE #962: Client unable to ready for new round after another round ends
## Current Behavior

After a round ends, either by blowing the nuke or an admin ending it, the joining clients seem to be unable to ready up for the next round. The issue doesn't seem present for the host.

Notice the ready up buttons in the image below.

SS3D_RsZyeGwoGU

## Replicate Bug

1. Open a host and a client window.
2. Ready up on both and launch the round from the host.
3. End the round via admin button or using the nuke disk in the nuke.
4. Make sure both the host and client screens revert to the server lobby.
5. See if the Ready Up button is selectable on the client window.

### PR DESCRIPTION
**Pull request by joaoburatto**
## Summary

closes #962

### CODE REVIEW

**Review by TaylorNAlbarnaz — APPROVED** [review]
fixes everything without creating any new bugs, as far as i tested

File: Assets/Scripts/SS3D/Systems/Lobby/UI/LobbyReadyView.cs [hunk 1]
```diff
@@ -18,15 +18,23 @@ public sealed class LobbyReadyView : NetworkActor
         [SerializeField] private ToggleLabelButton _readyButton;
         [SerializeField] private LabelButton _embarkButton;
 
-        protected override void OnAwake()
+        protected override void OnAwake()
```
Comment (cosmiccoincidence) [inline Assets/Scripts/SS3D/Systems/Lobby/UI/LobbyReadyView.cs:21]: ?
