### PR TITLE
Play mode tests

### LINKED ISSUE #984: Add automatic client testing
## Summary

Each new PR tend to break previously implemented features. It makes development slow and cumbersome.
As the game complexity is going to increase, it'll be more and more difficult to test edge case situations, such as exotic settings from atmos engineer, station explosions, uncommon entities and event ...

We currently lack the ability to do any sort of automatic testing client side, tocheck if nothing breaks, and to easily test exotic scenarios. 

We don't necessarily want it to be fully automatic, but we want at least reviewers to be able to launch some tests and see if they pass.

here's @Ryan089 suggestion on doing that : 

> **what if we created a command from the client to the server to load a "test mode", then had some API for setup / arrange / teardown stuff on the server from the client. So the reviewer could create a development build to run the server, then run the client tests from within Unity (which orchestrate the actions of the server).**

The idea would be to be able to reproduce these exotic scenarios and tests with minimal efforts, such as clicking on a script, that would set up through commands only player spawning, and creating the conditions for a given scenario.

One component of this process should probably be ` [UnityTest]` : 
https://docs.unity3d.com/Packages/com.unity.test-framework@1.1/manual/reference-attribute-unitytest.html

The kind of test we'd like to do automatically would be : 

- Check if clients can connect correctly when the server launch the round.
- Check if client UI is working as expected, such as dropping item sprite on it should show the sprite in the UI slots.
- Check if client can receive damage as expected in multiple scenarios.
-  Check if an item enters the inventory once the player has picked it up.
- ...

Maybe [that video](https://www.youtube.com/watch?v=X673tOi8pU8) about doing something similar on UE can help or provide some inspirations .

### LINKED ISSUE #1025: Add tests for late joining, early joining
## Summary

We need tests to check if clients can late join, early join without any issues getting in game.
This issue is work in progress, we need to define precisely the tests we want.

## Dependencies

Issue #984

### PR DESCRIPTION
**Pull request by stilnat**
## Summary

Taking back Ryan's work #1050 to have in game play mode tests. Citing Ryan : 

**Edit Mode**

EditMode tests have been restructured to be more clear in what they are testing. Some PlayMode tests have been created. PlayMode tests require a build to be made, and most will automatically launch the build (where required) in order to establish client / server connections. I have restricted Playmode tests from running in github actions, intent is for this restriction to remain even after PR is complete and merged. 

**Play Mode**

These are play mode tests that are intended to test game systems under runtime conditions. For example, a test could confirm the player ability to effectively embark onto the station at round start, and with late join etc.
Known Issue Replication [Not yet complete]

**Known Issue Replication**

These are play mode tests that are intended to provide actions to reliably reproduce a specific fault (as listed in github issues) under a variety of conditions, such as different server / host / client arrangements. This allows contributors attempting to resolve those faults to more clearly understand the problem, and thoroughly check whether all aspects of the issue have been resolved prior to pushing their solution.

## Todo

- [x] Make the pickup test accessible to latejoin/host.
- [x] Fix the unworking tests when launched individually.
- [x] Fix the mouse input and action binding.
- [x] Document stuff correctly.
- [x] Move PlayerCanMoveInEachDirectionCorrectly, AssertCorrectPlayerPositionOnAxis, MoveInDirection in testHelper and PlayerTestRepository.
- [x] Complete PlayerCanMoveInEachDirectionCorrectly for host
- [x] Remove and simplify most of the test hierarchy, it's causing more trouble than it helps.

## Changes to Files

- add empty scene for tests.
- Add a few TryGet methods instead of simple get.
- Replaced old input.mouseposition with new input system.
- remove itemCommandUtilities to put functionalities into item system (changes in itemcommand folder)
- add a command spawn item in item system.
- Add a string utility to convert a string to a given enum value.
- Make all tests inherit from our own custom testing class SpessTest.

## Known issues

- Sometimes (rare behavior) the tests start to fail for no clear reasons, most probably when some code is changed. Closing and opening again the editor fix it.

## How to test it

- Build the game (necessary for play tests testing clients)
- Open the test runner (Window -> General -> Test runner)
- Select play mode, you should see a list of different tests.
- Just double click on one of them to run it.
- Wait until it reach completion, there's nothing else to do.
- Note that you need to do that for every test (need to be automatized)

image

## Future work

- **Free Play** 
These are play mode tests that do not contain Assertions, but rather a free play loop that can be exited by a certain key combination. The purpose of this is to easily load the game under specific configurations. This will allow specific scenarios to be created that can be playtested by a reviewer.
- Add many more tests.
- Add better support for mouse, it's currently only supporting left click, and left click is only doing primary interactions where the click happened.
- Make all edit mode test inherit from SpessEditModeTest
- Find a way to make all tests run in a row as expected (currently working one by one).
- Add play tests to CI
- Recording scenario ? That's highly hypothetical, but finding a way to record a series of input and play them again in a test, making assertions along the way, is probably the best way to test complex dynamics without too much effort.
Helpful thread : https://forum.unity.com/threads/recording-and-replaying-input.739187/
- Load empty scenes and build on it for specific test purpose.
- Divide TestHelpers into multiple classes, dedicated to different help,such as TestMovementHelpers, TestInteractionHelpers...
-  Do something similar with PlayModeTestRepository.

## Fixes (optional)
closes #1025
closes #984

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
High priority because at least 2 other PRs are waiting for this one to be merged first.

File: Assets/Scripts/Tests/Common/SpessEditModeTest.cs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+using NUnit.Framework;
+
+namespace SS3D.Tests
+{
+    /// <summary>
+    /// Base for edit mode tests
+    /// </summary>
+    public abstract class SpessEditModeTest: SpessTest
```
Comment (joaoburatto) [inline Assets/Scripts/Tests/Common/SpessEditModeTest.cs]: Remove the `Spess` prefix, its cool but its better to avoid funny stuff.

File: Assets/Scripts/Tests/Common/SpessTest.cs [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+using UnityEngine;
+using UnityEngine.TestTools;
+
+namespace SS3D.Tests
+{
+    /// <summary>
+    /// Base testing class, inherited by PlayModeTest and EditModeTest.
+    /// </summary>
+    [TestFixture]
+    public abstract class SpessTest
```
Comment (joaoburatto) [inline Assets/Scripts/Tests/Common/SpessTest.cs]: Remove the `Spess` prefix, its cool but its better to avoid funny stuff. If the Test name conflicsts with something maybe try `UnitTest`

**Review by joaoburatto — DISMISSED** [review]

**Comment by cosmiccoincidence** [comment]
What's the hold up here?

**Comment by stilnat** [comment]
@cosmiccoincidence someone other than contributors to it need to test it a bit.

**Comment by cosmiccoincidence** [comment]
Fair. I would review it but I don't know much about testing or how to run them. I would just end up having to ask of the contributors about it and basically follow some steps given to me by them, which doesn't seem much better or different even.

I see that this was started by Ryan and then finished by you, has Ryan taken a look at this recently? If the two of you think it's good I would be satisfied with that. Having a 3rd party look at would be nice but if Ryan takes a look then we already have 2 sets of eyes on it, both of which with Maintainer privileges.

Also consider writing a guide on how to run the tests on the GitBook maintainer guide.

**Comment by stilnat** [comment]
I'll add doc once merged. I don't think Ryan took a look at this recently no, but most of it is Ryan's work, I simplified it a bit.

**Review by cosmiccoincidence — CHANGES_REQUESTED** [review]
Resolve conflict please

**Comment by stilnat** [comment]
Closed for now, to allow moving forward on other part of the code base.

**Comment by stilnat** [comment]
Fixed, and updated to work with the current build.
All play tests should pass.

**Comment by cosmiccoincidence** [comment]
I would review this but I am unfamiliar with the testing "system" that is already implemented and ultimately don't know exactly how to run these tests in order to properly review the PR.

**Comment by stilnat** [comment]
@cosmiccoincidence my request was more to let you know your previous request can be dismissed. However that made me think I should add a step by step guide to use it, so I'll do that (probably this weekend).

**Review by cosmiccoincidence — DISMISSED** [review]

**Review by cosmiccoincidence — APPROVED** [review]
Works as expected. Wish someone could have looked at the code a bit more but it's time this get merged already.

Don't forget to document this on gitbook.
